#!/bin/sh

regex='@sesame\.com\.tn$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]] ;
then
   echo your email $email satisfies Git policy
   exit 0
else
    echo "your email $email doesn't satisfies Git policy"
    exit 1
fi
   
